### ISSUE TITLE
Failed Imports Not in Summary

### ISSUE THREAD

**Issue by irmerk** [bookworm-reads/server#12]
> investigate imports where failed imports are not showing in summary

## Steps to Reproduce

1.
2.
3.
4.

## Context

![Image](https://github.com/bookworm-reads/server/assets/36460856/f9ed3ebd-df3b-4753-bbff-1c338acacc5f)

> importData.failed = 2 but importData.failedImports = 0 ? 

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by ameliagoodman** [comment]
this has been fixed :)
